### ISSUE TITLE
Unable to open files :(

### ISSUE THREAD

**Issue by crertel** [scout119/beamdasm#195]
This is great!

I'm unfortunately unable to get it to load any beam files; debugging, it gives:

![image](https://user-images.githubusercontent.com/1707779/121105795-64006200-c7ca-11eb-9e11-a70bea1eba2e.png)

VSCode info version:

![image](https://user-images.githubusercontent.com/1707779/121105899-93af6a00-c7ca-11eb-91c4-1131c43530ff.png)

I think this also may be due to me running on Linux.

```Linux attenborough 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by scout119** [comment]
I think the issue is with vscode.workspace.createFileSystemWatcher. I'll see what I can do to work around the problem.
Thank you for reporting this.

**Comment by crertel** [comment]
Thank you!

**Comment by crertel** [comment]
Hello! Sorry to be a bother--did you have any luck with this?

**Comment by crertel** [comment]
I submitted a patch for this on Linux! #268
