### ISSUE TITLE
Does not open with VSCode 1.31.1

### ISSUE THREAD

**Issue by yoctozepto** [scout119/beamdasm#4]
The error I get is:
> Unable to open 'bounce.beam_code': The value of "offset" is out of range. It must be an integer. Received NaN.

**Comment by scout119** [comment]
Thank you for reporting. Can you please share the file?

**Comment by yoctozepto** [comment]
Sorry! I did not notice GitHub rejected the Erlang files. Here they are now, in a ZIP file.

[bounce.zip](https://github.com/scout119/beamdasm/files/2886311/bounce.zip)

**Comment by kana-sama** [comment]
It fails for me in every beam file.

**Comment by scout119** [comment]
Same error?

**Comment by kana-sama** [comment]
Yes

**Comment by trbngr** [comment]
same

**Comment by scout119** [comment]
New version of the extension has been published to the marketplace
