### ISSUE TITLE
Cannot read property 'ar' of undefined

### ISSUE THREAD

**Issue by Schultzer** [scout119/beamdasm#6]
Hi,

Thanks for this extension.

When I try to open some of my beam files there have been compiled with code coverage I get this error `Unable to open 'Elixir.Myapp.beam_code': Cannot read property 'ar' of undefined.`

This is on OTP 22.0.2 and Elixir master

**Comment by KineticCookie** [comment]
Encountered the same issue on vs code:
```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-25-generic snap
```

**Comment by jvantuyl** [comment]
Same here.

Elixir 1.8.1 and 1.9.4 and OTP 22.

**Comment by scout119** [comment]
Sorry for taking so long to address this. Can you please provide the beam file? 
Thank you.
